### ISSUE TITLE
Can not compile with conduit >= 1.0 

### ISSUE THREAD

**Issue by s9gf4ult** [jhance/vector-conduit#4]
This package is not compatible with conduit >= 1.0

`Data/Conduit/Vector.hs:26:20: Not in scope: 'sourceState'`

`sourceState` is not any more in `Data.Conduit` since conduit 1.0 

Add version restrictions or fix please.
